cc_library(
    name = "discrete",
    srcs = glob([
        "*.cpp",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//gtsam:global_includes",
        "//gtsam/base",
        "//gtsam/base/treeTraversal",
        "//gtsam/inference",
        "@eigen",
    ],
)
